# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_tag', '0012_auto_20151202_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='command',
        ),
        migrations.AddField(
            model_name='command',
            name='fault',
            field=models.CharField(default=b'fire', max_length=20),
        ),
        migrations.AlterField(
            model_name='command',
            name='team',
            field=models.IntegerField(default=1),
        ),
    ]
