# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot_tag', '0013_auto_20151202_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='fault',
            new_name='command',
        ),
    ]
