# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('robot_tag', '0014_auto_20151202_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fault',
            old_name='attacker',
            new_name='victim',
        ),
        migrations.AddField(
            model_name='fault',
            name='when',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 9, 5, 35, 1, 766821, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
